### ISSUE TITLE
Damage values slightly incorrect

### ISSUE THREAD

**Issue by Gindi4711** [frankmorgner/foe-battle-simulator#1]
I think the damage values differ a bit from the correct ingame values.

Here is the values I found:
0-0 | 0 | 0,153846154
0-1   Damage | 0,153846154 | 0,251572327
0-2   Damage | 0,25210084 | 0,322580645
1-2   Damage | 0,323529412 | 0,344827586
1-3   Damage | 0,345323741 | 0,454545455
1-4   Damage | 0,455882353 | 0,509803922
2-4   Damage | 0,510204082 | 0,597826087
2-5   Damage | 0,6 | 0,697674419
3-5   Damage | 0,698924731 | 0,798165138
3-6   Damage | 0,8 | 0,921052632
4-6   Damage | 0,922330097 | 1,107142857
4-7   Damage | 1,111111111 | 1,210526316
5-7   Damage | 1,212121212 | 1,612903226
6-7   Damage | 1,621621622 | 1,655172414
6-8   Damage | 1,666666667 | 2,25
7-8   Damage | 2,258064516 | 2,941176471
7-9   Damage | 2,962962963 | 3,346153846
8-9   Damage | 3,392857143 | 5,833333333
9-9   Damage | 6 | 9,090909091
9-10   Damage | 9,111111111 | 18,5
10-10   Damage | 19 | 190

**Comment by frankmorgner** [comment]
The empirical data from FoEhints is a little bit newer and I did not find your numbers in the [referenced spreadsheet](https://forum.en.forgeofempires.com/index.php?threads/the-damage-calculator.25048/)... Anyway, I could think of two different configurations for the actual values until we have some better source...

**Comment by Gindi4711** [comment]
There is a hidden worksheet "Sheet3“. Go to row 1000. This is where data starts. We could take a few samples in GBG by slowly increasing attrition to check the results. Values of Foehints seem to be rounded values of the ones in the spreadsheet.
