### ISSUE TITLE
Bonus attack must be applied after attack bonus

### ISSUE THREAD

**Issue by Gindi4711** [frankmorgner/foe-battle-simulator#2]
attack  = (attacker.attack  + attacker.bonus_attack(defender))  * (100 + boost_attack)  / 100

Here you are applying the bonus attack first and then attack boost.

Example Nailstorm attacking artillery at +400% attack bonus:
(650 + 300) * (100 + 400) / 100 = 950 * 500% = 4750

The correct calculation would be to apply attack boost first and then bonus attack:
650 * (100 + 400) / 100 + 300 = 650 * 500% + 300 = 3550

**Comment by frankmorgner** [comment]
Can this be verified in-game or can you give a source for that?

**Comment by Gindi4711** [comment]
It is not directly shown ingame, but you can verify it by looking at estimated damage and looking the factor up. With your calculation it does sometimes not match.

**Comment by frankmorgner** [comment]
OK, ingame the difference is obviously visible: the players boosts are not applied to the attack/defense bonus. That's a pitty, since it renders the bonus almost useless considering huge attack/defense boosts (or high attrition)...
